### ISSUE TITLE
Questions about the provided dataset

### ISSUE THREAD

**Issue by LouisDo2108** [HansiZeng/PAG#1]
Hi @HansiZeng,

Thank you for your awesome work and for sharing the code with the community. I have a few questions regarding the dataset.

Could you please explain the general purpose of the msmarco-full/all_train_queries folder? Specifically, I'm confused about the pseudo-queries.tsv file with around 482k queries and the train-queries/raw.tsv file with around 985k queries. Why there are additional pseudo queries for  the pre-training stage?

Thank you.

**Comment by LouisDo2108** [comment]
Hi @HansiZeng ,

Could you please kindly answer my question?

Thank you.

**Comment by HansiZeng** [comment]
Hi,
985K queries correponds to 1M documents.
If you see our [RIPOR](https://arxiv.org/pdf/2311.09134) paper, in Table 4 (Appendix), we also train and evaluate our model on MS MARCO 1M setting.
I just want to make 1M and 8.8M settings somehow comparable. 

Anyway, Using the original MS MARCO train queries with around 532K should give you very similar results. But remember to double the training epochs. For instance, if the training epochs for 985K queries are 50, then 532K queries should better be 100.

**Comment by WindSighiii** [comment]
So, is raw the combination of the original training queries and the pseudo queries?
